apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30100
      protocol: TCP
