apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: dev
  name: limit-range-dev
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: 0.5
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: poddefault
  namespace: dev
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: container-name
      image: nginx:alpine
