apiVersion: v1
kind: Secret
metadata:
  name: supersecreto
type: Opaque
data:
  user: dXNlci1zdXBlcnNlY3JldA==
  pass: RWxTdXAzclNlY3JFVDAyMDU3Iw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: contenedor1
          image: nginx:alpine
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: pass
