apiVersion: v1
kind: Namespace
metadata:
  name: qas
  labels:
    name: qas
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-pod
  namespace: qas
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: qas
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
