apiVersion: v1
kind: Namespace
metadata:
  name: qas
  labels:
    name: qas
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-pod
  namespace: qas
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: qas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: 500M
              cpu: 500m
            limits:
              memory: 500M
              cpu: 500m
