apiVersion: v1
kind: Pod
metadata:
  name: webserver-nginx
spec:
  containers:
    - name: web
      image: nginx:alpine
      resources:
        requests:
          cpu: "0.5"
          memory: "100Mi"
        limits:
          cpu: "1"
          memory: "200Mi"
