apiVersion: v1
kind: Pod
metadata:
  name: democpu
spec:
  containers:
    - name: democpu1
      image: vish/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
      args:
        - -cpus
        - "2"
