apiVersion: v1
kind: Pod
metadata:
  name: demoram
spec:
  containers:
    - name: demoram-container
      image: polinux/stress
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]
