version: "3.8"

services:
  nginx-service:
    build:
      dockerfile: dockerfiles/nginx.dockerfile
      context: .
    container_name: nginx-service
    ports:
      - "9100:80"
    depends_on:
      - php-service
      - mysql-service

  php-service:
    build:
      dockerfile: dockerfiles/php.dockerfile
      context: .
    container_name: php-service

  mysql-service:
    image: mysql:8
    container_name: mysql-service
    env_file:
      - ./env/mysql.env
    ports:
      - "3320:3306"

  composer-service:
    build:
      dockerfile: dockerfiles/composer.dockerfile
      context: .
    volumes:
      - ./src:/var/www/html

  artisan-service:
    build:
      dockerfile: dockerfiles/php.dockerfile
      context: .
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
